---
driver:
  name: terraform
  root_module_directory: test/fixtures
  parallelism: 4
  verify_version: false
  command_timeout: 1200

provisioner:
  name: terraform

platforms:
  - name: "aws"

suites:
  - name: organizational-cspm
    driver:
      root_module_directory: test/fixtures/organizational-cspm
